- hosts: all
  become: yes
  tasks:
  - name: Install packages 
    ansible.builtin.apt:
      name: 
        - apache2
        - tree
        - unzip
      state: present
      update_cache: yes

  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes


  - name: Execute the command in remote shell
    ansible.builtin.shell: sudo useradd tim
    ignore_error: yes
  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: tim



